tools:
  external_code_coverage:
    timeout: 600
  php_analyzer: true
  php_cpd: true
  php_code_sniffer:
    enabled: true
    config:
      standard: custom
  php_mess_detector: true
  sensiolabs_security_checker: true
  php_pdepend: true