---
Name: omniroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'paymentendpoint/$Identifier/$Status/$ReturnURL' : 'PaymentGatewayController'
    'dev/payment' : 'PaymentDevelopmentAdmin'
